baseurl = "https://blog.ollietroward.com"
languageCode = "en-uk"
theme = "hello-friend"
paginate = 5
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[params]
  author = "Ollie Troward"
  github = "https://github.com/ollie-troward"
  facebook = "https://facebook.com/ollie.troward"
  sitename = "Blog ğŸ‘¨ğŸ»â€ğŸ’»"
  twitter = "@ollietroward"
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Show reading time in minutes for posts
  showReadingTime = true

[languages]
  [languages.en]
    title = "Blog ğŸ‘¨ğŸ»â€ğŸ’»"
    subtitle = "Ollie Troward"
    keywords = "blog software health ollie troward"
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "02/01/2006"
    dateFormatList = "02/01/2006"

    [languages.en.params.logo]
      logoText = "Ollie Troward"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "website"
        name = "Website"
        url = "https://ollietroward.com"
#    [languages.en.menu]
#      [[languages.en.menu.main]]
#        identifier = "about"
#        name = "About"
#        url = "/about"
